### ISSUE TITLE
Опечатка?

### ISSUE THREAD

**Issue by ivanych** [melezhik/outthentic-dsl#1]
В документации, в разделе Captures, есть такой кусок:

```
[
    ['alex',    38 ]
    ['julia',   32 ]
    ['jan',     2  ]
]
```

Почему там 32? Вроде должно быть 25? Опечатка?

**Comment by melezhik** [comment]
Поправил. Да, жене, на самом деле 32 года. Но я сами понимаете решил дать "немного" меньше  ;-)

**Comment by melezhik** [comment]
d324b447c1d89df468beef3394fa44fa2c0b410a

**Comment by ivanych** [comment]
Но тесты обнаружили ошибку:)

**Comment by melezhik** [comment]
good! ;-)
